[project]
name = "pdf-text-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymupdf>=1.25.4",
    "pymupdf4llm>=0.0.19",
]
